parameters:
    env(DATABASE_HOST): '127.0.0.1'
    env(DATABASE_PORT): 5432
    env(DATABASE_USER): 'postgres'
    env(DATABASE_PASSWORD): ''
    database: '%env(string:DATABASE_DATABASE)%'
    database_host: '%env(string:DATABASE_HOST)%'
    database_port: '%env(int:DATABASE_PORT)%'
    database_user: '%env(string:DATABASE_USER)%'
    database_password: '%env(string:DATABASE_PASSWORD)%'
doctrine:
    dbal:
        charset: utf8
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        dbname: '%database%'
        driver: 'pdo_pgsql'
        host: '%database_host%'
        port: '%database_port%'
        server_version: '11.0.7'
        user: '%database_user%'
        password: '%database_password%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
