services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Payload,Exception,Migrations,Tests,Response,Kernel.php,Translates,Templates}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\EventListener\ApiExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    App\EventListener\UserListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: prePersist, priority: 255 }

    App\EventListener\TransactionListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: prePersist, priority: 255 }

    converter.payload:
        class: App\ParamConverter\PayloadConverter
        tags:
            - { name: request.param_converter, priority: -50, converter: payload }

    xml.normalizer:
        class: App\ArrayNormalizer\XmlNormalizer

    App\Service\Payload\Factory\DataHelper:
        public: false
